name: Docker

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build and Run
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Git Bash
        shell: bash
        run: |
          choco install git -y
          echo 'export PATH="/mingw64/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc
          git config --global core.autocrlf input
          git config --global core.longpaths true

      - name: Run the Docker image
        run: |
          ./scripts/install_submodules.sh
          docker compose build
          docker compose run machine build
          docker compose up -d
